deployment:
  tasks:
    - export DEPLOYPATH=/home/mabelriart/public_html/encuesta
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R packages $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp .gitattributes $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp artisan $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp gulpfile.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH

    